package com.envoy.rater.orm;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.envoy.rater.orm.Game;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GAME".
*/
public class GameDao extends AbstractDao<Game, Long> {

    public static final String TABLENAME = "GAME";

    /**
     * Properties of entity Game.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property GameName = new Property(1, String.class, "gameName", false, "GAME_NAME");
        public final static Property ConsoleName = new Property(2, String.class, "consoleName", false, "CONSOLE_NAME");
        public final static Property GameImage = new Property(3, byte[].class, "gameImage", false, "GAME_IMAGE");
        public final static Property IsGameFinished = new Property(4, Boolean.class, "isGameFinished", false, "IS_GAME_FINISHED");
        public final static Property StarsNumber = new Property(5, Integer.class, "starsNumber", false, "STARS_NUMBER");
    };

    private DaoSession daoSession;


    public GameDao(DaoConfig config) {
        super(config);
    }
    
    public GameDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GAME\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"GAME_NAME\" TEXT," + // 1: gameName
                "\"CONSOLE_NAME\" TEXT," + // 2: consoleName
                "\"GAME_IMAGE\" BLOB," + // 3: gameImage
                "\"IS_GAME_FINISHED\" INTEGER," + // 4: isGameFinished
                "\"STARS_NUMBER\" INTEGER);"); // 5: starsNumber
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GAME\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Game entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String gameName = entity.getGameName();
        if (gameName != null) {
            stmt.bindString(2, gameName);
        }
 
        String consoleName = entity.getConsoleName();
        if (consoleName != null) {
            stmt.bindString(3, consoleName);
        }
 
        byte[] gameImage = entity.getGameImage();
        if (gameImage != null) {
            stmt.bindBlob(4, gameImage);
        }
 
        Boolean isGameFinished = entity.getIsGameFinished();
        if (isGameFinished != null) {
            stmt.bindLong(5, isGameFinished ? 1L: 0L);
        }
 
        Integer starsNumber = entity.getStarsNumber();
        if (starsNumber != null) {
            stmt.bindLong(6, starsNumber);
        }
    }

    @Override
    protected void attachEntity(Game entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Game readEntity(Cursor cursor, int offset) {
        Game entity = new Game( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // gameName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // consoleName
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3), // gameImage
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // isGameFinished
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5) // starsNumber
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Game entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGameName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setConsoleName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGameImage(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
        entity.setIsGameFinished(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setStarsNumber(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Game entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Game entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
